services:
  web:
    build: .
    container_name: chiquicode
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chiquicode.rule=Host(`chiquicode.com`) || Host(`www.chiquicode.com`)"
      - "traefik.http.services.chiquicode.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
